username = input("Введите имя пользователя: ")
print("Имя пользователя: ",username)
title = input("Введите заголовок заметки: ")
print("Заголовок заметки: ",title)
content = input("Введите описание заметки: ")
print("Описание заметки: ",content)
status = input("Введите статус заметки: ")
print("Статус заметки: ", status)
created_date = input("Введите дату создания заметки: ")
print("Дата создания заметки: ", created_date)
issue_date = input("Введите дату завершения заметки: ")
print("Дата завершения заметки: ", issue_date)