note = []
username = input("Введите имя пользователя: ")
content = input("Введите содержание заметки: ")
status = input("Введите статус заметки: ")
created_date = input("Введите дату создания заметки: ")
issue_date = input("Введите дату окончания заметки: ")
title = input("Введите заголовок №1: ")
title1 = input("Введите заголовок №2: ")
title2 = input("Введите заголовок №3: ")
titles = [title, title1, title2]
note.append(username)
note.append(content)
note.append(status)
note.append(created_date)
note.append(issue_date)
note.append(titles)
print("\nСобранные данные о заметке:")
print(f"Имя пользователя: {note[0]}")
print(f"Содержание заметки: {note[1]}")
print(f"Статус заметки: {note[2]}")
print(f"Дата создания: {note[3]}")
print(f"Дата окончания: {note[4]}")
print("Заголовки:")
for i, title in enumerate(note[5], 1):
    print(f"  Заголовок №{i}: {title}")
print("\nСтруктура заметки:", note)
