username = input("Имя пользователя")
print("Имя пользователя",username)
title = input("Заголовок заметки")
print("Заголовок заметки",title)
content = input("Описание заметки")
print("Описание заметки",content)
status = input("Статус заметки")
print("Статус заметки", status)
created_date = input("Дата создания заметки")
print("Дата создания заметки", created_date)
issue_date = input("Дата истечения заметки")
print("Дата истечения заметки", issue_date)